services:
  lymify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    environment:
      - PORT=3300
      - SPOTDL_API_URL=http://spotdl:8800
    volumes:
      - ./music:/usr/src/app/music
    depends_on:
      - spotdl

  spotdl:
    image: spotdl/spotify-downloader:latest
    command: ["web", "--host", "0.0.0.0", "--port", "8800", "--keep-alive", "--web-use-output-dir"]
    ports:
      - "8800:8800"
    volumes:
      - ./music:/music
      - ./.spotdl-cache:/app/.spotdl-cache
    restart: unless-stopped
