services:
  lymify:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      target: development
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=development
      - PORT=3300
      - SPOTDL_API_URL=http://spotdl:8800
    volumes:
      - ./music:/usr/src/app/music
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - spotdl
    command: ["npx", "nodemon", "src/server.js"]

  spotdl:
    image: spotdl/spotify-downloader:latest
    command: ["web", "--host", "0.0.0.0", "--port", "8800", "--keep-alive", "--web-use-output-dir"]
    volumes:
      - ./music:/music
      - ./.spotdl-cache:/app/.spotdl-cache
    restart: unless-stopped
